###
POST http://localhost:9000/user HTTP/1.1
Content-Type: application/json

{
    "userName" : "MisterTiene",
    "firstName" : "Franco",
    "lastName" : "Ledesma",
    "email" : "juanfledesma18@gmail.com",
    "dni" : 48523695,
    "phone" : 3547582365,
    "address": {
        "street" : "FuegoTiene",
        "number" : 496,
        "floor" : 2
    },
    "birthdate" : "07/01/1998",
    "loyaltyPoint" : 10,
    "state" : "active",
    "type" : "admin"
}
