###
POST http://localhost:9000/books HTTP/1.1
Content-Type: application/json

{
  "name":"El Silencio de los corderos",
  "author": ["Thomas Harris"],
  "editorial":" Editorial Martin's Press",
  "price":299.15,
  "category":["6344638497cc65387427785c"],
  "synopsis":"A Clarice Starling, joven y ambiciosa estudiante de la academia del FBI, le encomiendan que entreviste a Hannibal Lecter, brillante psiquiatra y despiadado asesino, para conseguir su colaboración en la resolución de un caso de asesinatos en serie.",
   "format": "paperback",
   "edition":1,
   "language":"ES",
   "ISBN":20,
   "stock":20,
    "image":"data.jpg"

}


# {
#   "name":"yoyo",
#   "author": ["fernando", "yoyo"],
#   "editorial":"fran",
#   "price":255,
#   "category":["6344638497cc65387427785c","6344638497cc65387427785a"],
#   "synopsis":"blablabla",
#    "format": "cover",
#    "edition":45,
#    "language":"ES-IN",
#    "ISBN":2525,
#    "rating":0,
#    "stock":10,
#    "reviews":[],
#     "image":"bblbla.jpg"

# }

###
PUT  http://localhost:9000/books/update/6344ac235c59544ca8bf76ac HTTP/1.1

{
  "name":"EL Silencio de Merlin"
}